server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: tao121314
    driver-class-name: com.mysql.jdbc.Driver

#      discovery:
#        cluster-name: HZ
mybatis:
  type-aliases-package: cn.tao.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.tao: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: #eureka地址信息
#      defaultZone: http://127.0.0.1:10086/eureka