server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: tao121314
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:80 #nacos服务地址
#      discovery:
#        namespace: c2dda5a6-044e-4693-835f-037f364f62ab #dev环境
mybatis:
  type-aliases-package: cn.tao.user.pojo
  configuration:
    map-underscore-to-camel-case: true
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #负载均衡规则
logging:
  level:
    cn.tao: debug
pattern:
  dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: #eureka地址信息
#ribbon:
#  eager-load: true
#    enabled: true
#    clients:
#      - userservice

#      defaultZone: http://127.0.0.1:10086/eureka
feign:
  httpclient:
    enabled: true #支持httpclient
    max-connections: 200
    max-connections-per-route: 50